<?php
class HBPublic extends HBPlugin
{

	protected function init()
	{
		$this->add_filter('image_send_to_editor');
	}

	/**
	 * Replace the HTML code with a shortcode with the same parameters so the image code is
	 * generated by the_content().
	 *
	 * @param $html string
	 *        	generated HTML for the inserted image
	 * @param $id int
	 *        	image ID
	 * @param $caption string
	 *        	caption for the image
	 * @param $title string
	 *        	title for the image
	 * @param $align string
	 *        	image alignment
	 * @param $url string
	 *        	source URL of the image
	 * @param $size string
	 *        	size for the inserted image
	 * @return formatted shortcode
	 */
	function image_send_to_editor($html, $id, $caption, $title, $align, $url, $size)
	{
		return '[hb-image id="' . $id . '"]';
	}

	function hb_image_shortcode($atts, $content = null, $code = "")
	{
	}
}
